apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-python
  labels:
    app.kubernetes.io/name: web-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-app
        image: glebosotov/inno-devops-labs-app-python
        # ports:
        # - containerPort: 5000