apiVersion: v1
kind: Pod
metadata:
  name: app-python
spec:
  containers:
  - name: web-app
    image: glebosotov/inno-devops-labs-app-python
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"