name: Python docker image upload

on: [push]

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      python: ${{ steps.filter.outputs.python }}
      flutter: ${{ steps.filter.outputs.flutter }}
    steps:
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          python:
            - 'app_python/**'
          flutter:
            - 'app_flutter/**'

  build:
    needs: changes
    if: ${{ needs.changes.outputs.python == 'true' }}
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout 
      uses: actions/checkout@v2
    -
      name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: "{{defaultContext}}:app_python"
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/inno-devops-labs-app-python:latest
        cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/inno-devops-labs-app-python:buildcache
        cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/inno-devops-labs-app-python:buildcache,mode=max
  